spring.application.name=text-translator-api

translation.api.url=http://localhost:5000/translate
translation.api.backup-url=https://libretranslate.com/translate

voicerss.api.key=c8adaa59feec400dbeee5251777f1ec7
voicerss.api.url=https://api.voicerss.org/

# Redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:}